### ISSUE TITLE
Peer Review by Aliza Mithwani

### ISSUE THREAD

**Issue by alizamithwani** [Wang20030509/Study_of_Death_Registry_Statistics#2]
**Opening statement summary**

I am reviewing Doran Wang's paper on the effect of the seasons on death rates in Toronto

**Strong positive points**

I liked the concept of figure 1: you can see that death counts are somewhat higher in warmer months. The README is very well written.

**Critical improvements needed**

You haven't removed unused files from your repo (scripts: model, replications, models: first_model.rds, other: literature, datasheet). You haven't tested your data (03 script is missing). I believe you can comment out the install.packages (or remove it) after you have installed the package on your computer in the download data script. In downloading and cleaning files, the file you're referencing to write to is not reproducible on another person's computer as the path is specific to your computer. @fig-planes cross-reference isn't working on the pdf (i'm assuming you didn't mean to leave this in the qmd). Your introduction is incomplete as it doesn't introduce the topic or explain it. You haven't written an abstract. Your data section seems incomplete as it doesn't talk about the data source or context. Your introduction is incomplete too as it doesn't introduce the topic or explain it. You did not submit relevant sketches. You said ChatGPT chat history is available at inputs/llms/usage.txt but there is not inputs folder on your repo and you haven't actually updated the usage.txt file to show your chat history with ChatGPT.

**Suggestions for improvement:**

In regards to figure 1, I would have liked more explanation as to why other cities are there (i'm assuming you're comparing Toronto to other cities), is there a reason you picked these specific cities, and what period would you consider warm months for all these cities. So please explain what you are doing with this graph in the data section. Please ensure that all paths are reproducible on a computer that only has access to your repo. Please add an introduction and abstract. Please remove any irrelevant cross-references from your final submission and make sure all used cross-references are working as intended. Please upload your sketches and ChatGPT history, and remove any unused files/folders from your repo. Please test your data to ensure it is ready to work with and that the cleaning has worked.

**Please consider adding/changing/removing:**

Please remove unused files/folders
Please add an introduction and abstract
Please add a data section which explains sources and context
Please ensure all cross-references work (or remove irrelevant cross-references)
Please ensure all paths are reproducible
Please add sketches outlining your table/graph(s)
Please test your data
Please provide your chat history with ChatGPT

**Evaluation:** 

In terms of the topic chosen, the scripts and the code, this is a good first draft. It lacks content in the paper explaining sources, contexts and figures. The paper does a good job with references and the README. It lacks some required items like a script to test the data, abstract, introduction, LLM history, and sketches. I would score this a 50 out of 100 if it were up to me.

**Estimated mark:**

0 out of 100.

**Reason:**

Your first draft is good in terms of the 3 scripts completed and submitted, the topic chosen and the figure included. However, according to the rubric, if you don't provide your chat history with ChatGPT, you get a 0.

**Comment by Wang20030509** [comment]
thanks for your review!
